---
title: "Experience"
---

- Professor of Production and Systems Engineering
  - Federal Centre for Engineering Studies and Technological Education - CEFET/RJ
  - August 2006 – Present
    Responsibilities:
    - Since 2025: Director of Strategic Planning (Chief Strategy Officer)
    - 2023-2025: Head of the Higher Education Department.
    - 2019-2021: Head of the Production Engineering Course Coordination of the Higher Education Department.
    - 2016-2018: Head of Production and System Engineering Graduate Program.
    - 2015-2016: Head of the Production Engineering Distance Course Coordination of the Higher Education Department.
    - 2011-2014: Director of Management and Budget (Chief Administrative Officer)

- Network Manager
  - Physics Institute, IF/UFRJ
  - January 1993 – January 2005

- Distributed Computer Control System Expert
  - European Organization for Nuclear Research - CERN
  - January 1993 – January 2005

- Network Manager
  - Applied Mathematics Laboratory, LABMA- IM/UFRJ
  - January 1992 – January 1993
